### ISSUE TITLE
带有@RequestMapping定义的接口没有接口文档

### ISSUE THREAD

**Issue by junziqiao** [liuzhihang/doc-view#49]
**Bug 描述**
简要描述 Bug 信息

**Version**
 - Doc View: [e.g. v1.2.5]
 - IDEA [e.g. 2022.1]

**Bug 详情**
异常日志、可能导致的原因、参数信息等
![image](https://user-images.githubusercontent.com/41858086/164214894-3d2db9c8-bf70-4601-addc-523c29b0664a.png)

**Comment by liuzhihang** [comment]
接口，这个是 Feign 的接口么，现在是需要带 FeignClient 注解才可以识别，你试一下。

**Comment by junziqiao** [comment]
不是的，我这边提供依赖出去，我这边就是普通接口定义

**Comment by junziqiao** [comment]
就是feiginClient和Controller抽出来的公共代码

**Comment by liuzhihang** [comment]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/26057042/164967911-51e04876-ce36-4d10-b12b-01333ff760ed.png">
这个可以试着勾上，具体你的这种抽出来公共的，我确实没有考虑。

**Comment by junziqiao** [comment]
谢谢

**Comment by junziqiao** [comment]
java.lang.IllegalStateException: Duplicate key 查询收货明细 (attempted merging values DocView(psiClass=PsiClass:PmsReceiptOrderApi, psiMethod=PsiMethod:getReceiptOrderDetailList, docTitle=收货, classTags=null, tags=null, name=查询收货明细, desc=查询收货明细, domain=null, path=PmsReceiptOrderApi#getReceiptOrderDetailList, method=Dubbo, changeLog=null, headerList=null, reqRootBody=com.liuzhihang.doc.view.dto.Body@15eb879b, respRootBody=com.liuzhihang.doc.view.dto.Body@7018b7e7, reqParamList=null, reqExample={
    "orderDetailId": 0,
    "orderDetailIdList": [
        0
    ],
    "purchaseTypeList": [
        0
    ],
    "purchaseType": 0,
    "receiptOrderId": 0
}, reqExampleType=json, respExample={
    "code": "",
    "msg": "",
    "info": [
        {
            "id": 0,
            "receiptOrderId": 0,
            "clothNo": "",
            "clothGuid": "",
            "orderNo": "",
            "status": 0,
            "produceOrderId": 0,
            "materialSku": "",
            "materialName": "",
            "materialColor": "",
            "colorNo": 0,
            "unit": "",
            "deliveryNum": "",
            "planPrice": null,
            "kilo": null,
            "shelvesNum": "",
            "lastUpdateTime": null,
            "originId": 0,
            "emptyDiff": "",
            "paperTube": "",
            "materialWidth": "",
            "materialWeight": "",
            "addTime": 0,
            "adminName": "",
            "isDelete": 0,
            "type": 0,
            "tankNo": "",
            "orderDetailId": 0,
            "purchaseNum": null,
            "receiveNum": null,
            "storageNum": null,
            "purchaseMan": "",
            "isPrintReceiptOrder": 0,
            "receiptTime": null,
            "receiptMan": "",
            "isReceipt": 0,
            "requirementNo": "",
            "createdBy": "",
            "createdTime": null,
            "isHistory": 0,
            "secBussiness": 0,
            "sourceType": 0,
            "purchaseType": 0,
            "garmentFactoryId": 0,
            "garmentFactory": "",
            "processDeliveryNo": ""
        }
    ]
}, remark=null, type=Dubbo) and DocView(psiClass=PsiClass:PmsReceiptOrderApi, psiMethod=PsiMethod:selectReceiptOrderDetailList, docTitle=收货, classTags=null, tags=null, name=查询收货明细, desc=查询收货明细, domain=null, path=PmsReceiptOrderApi#selectReceiptOrderDetailList, method=Dubbo, changeLog=null, headerList=null, reqRootBody=com.liuzhihang.doc.view.dto.Body@4082c52b, respRootBody=com.liuzhihang.doc.view.dto.Body@782631f, reqParamList=null, reqExample={
    "orderDetailId": 0,
    "orderDetailIdList": [
        0
    ],
    "purchaseTypeList": [
        0
    ],
    "purchaseType": 0,
    "receiptOrderId": 0
}, reqExampleType=json, respExample={
    "code": "",
    "msg": "",
    "info": [
        {
            "id": 0,
            "receiptOrderId": 0,
            "clothNo": "",
            "clothGuid": "",
            "orderNo": "",
            "status": 0,
            "produceOrderId": 0,
            "materialSku": "",
            "materialName": "",
            "materialColor": "",
            "colorNo": 0,
            "unit": "",
            "deliveryNum": "",
            "planPrice": null,
            "kilo": null,
            "shelvesNum": "",
            "lastUpdateTime": null,
            "originId": 0,
            "emptyDiff": "",
            "paperTube": "",
            "materialWidth": "",
            "materialWeight": "",
            "addTime": 0,
            "adminName": "",
            "isDelete": 0,
            "type": 0,
            "tankNo": "",
            "orderDetailId": 0,
            "purchaseNum": null,
            "receiveNum": null,
            "storageNum": null,
            "purchaseMan": "",
            "isPrintReceiptOrder": 0,
            "receiptTime": null,
            "receiptMan": "",
            "isReceipt": 0,
            "requirementNo": "",
            "createdBy": "",
            "createdTime": null,
            "isHistory": 0,
            "secBussiness": 0,
            "sourceType": 0,
            "purchaseType": 0,
            "garmentFactoryId": 0,
            "garmentFactory": "",
            "processDeliveryNo": ""
        }
    ]
}, remark=null, type=Dubbo))
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:133)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:180)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1239)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.liuzhihang.doc.view.ui.PreviewForm.buildDoc(PreviewForm.java:499)
	at com.liuzhihang.doc.view.ui.PreviewForm.<init>(PreviewForm.java:128)
	at com.liuzhihang.doc.view.ui.PreviewForm.getInstance(PreviewForm.java:149)
	at com.liuzhihang.doc.view.provider.DocViewLineMarkerProvider.lambda$createClassLineMarker$4(DocViewLineMarkerProvider.java:148)
	at com.intellij.codeInsight.daemon.NavigateAction.actionPerformed(NavigateAction.java:61)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:235)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:235)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.performAction(EditorGutterComponentImpl.java:2110)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.invokeGutterAction(EditorGutterComponentImpl.java:2052)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.mouseReleased(EditorGutterComponentImpl.java:2030)
	at com.intellij.openapi.editor.impl.EditorImpl.processMouseReleased(EditorImpl.java:2360)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.lambda$runMouseReleasedCommand$1(EditorImpl.java:3953)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:174)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.runMouseReleasedCommand(EditorImpl.java:3955)
	at com.intellij.openapi.editor.impl.EditorImpl$MyMouseAdapter.mouseReleased(EditorImpl.java:3838)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
